name: Build and Publish

on:
  push:
    branches:
      - stable
      - alpha

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore --warnaserror

      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal

      - name: Pack
        run: |
          dotnet pack NetCord -c Release --no-build
          dotnet pack NetCord.Services -c Release --no-build
          
      - name: Publish
        run: |
          dotnet nuget push NetCord/bin/Release/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -n -s https://api.nuget.org/v3/index.json --skip-duplicate
          dotnet nuget push NetCord.Services/bin/Release/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -n -s https://api.nuget.org/v3/index.json --skip-duplicate